

class LanguageTranslator:
    @classmethod
    def __init__(self):
        pass


    @staticmethod
    def get_translations():
        '''Contains a dictionary of translations for different languages'''
        translations = {"romanian": {"product_management": "Produktový management",
                                     "order_processing": "Zpracování objednávky",
                                     "reporting": "Reportování",
                                     "user_registration": "Registrace uživatele",
                                     "login_logout": "Přihlásit se / Odhlásit se",
                                     "change_language_currency": "Změnit jazyk a měnu",
                                     "reviews": "Recenze",
                                     "exit": "Opustit",
                                     "view_available_products": "zobrazit dostupné produkty",
                                     "view_all_customers": "zobrazit všechny zákazníky",
                                     "add_new_product": "přidat nový produkt",
                                     "update_existing_product": "aktualizovat stávající produkt",
                                     "remove_product": "odstranit produkt",
                                     "exit": "výstup",
                                     "item_id_is_exist_please_try_again": "ID položky existuje, zkuste to prosím znovu",
                                     "added_successfully": "adăugat cu succes",
                                     "updated_successfully": "Actualizat cu succes",
                                     "removed_successfully": "eliminat cu succes",
                                     "try_again_error_in_choice": "încercați din nou eroare la alegere",
                                     "you_are_not_logged_in_to_system_or_and_you_are_not_admin_manager_of_store": "nu sunteți autentificat la sistem sau și nu sunteți administratorul magazinului",
                                     "make_an_order": "face o comandă",
                                     "view_order_history": "vizualiza istoricul comenzilor",
                                     "update_order_status": "actualizați starea comenzii",
                                     "update_order_status_success": "actualizați starea comenziidssds ds",
                                     "this_is_the_list_of_product_for_purchase": "**aceasta este lista de produse de cumpărat**",
                                     "enter_0_in_item_id_to_stop": "introduceți 0 în id-ul articolului pentru a opri",
                                     "there_is_not_enough_quantity_of_this_product": "nu există suficientă cantitate din acest produs",
                                     "added_to_order_successfully": "adăugat la comandă cu succes",
                                     "the_product_order_process_has_been_stopped": "procesul de comandă de produse a fost oprit",
                                     "quantity_for_item": "cantitate pentru articol",
                                     "if you want to see your shopping cart and buy enter Y and if not enter N": "dacă vrei să-ți vezi coșul de cumpărături și să cumperi, introduceți Y și dacă nu introduceți N",
                                     "what_you_typed_is_invalid_pleas_try_again": "ceea ce ai introdus nu este valid, te rog să încerci din nou",
                                     "pay_pal": "paypal",
                                     "credit_cards": "Carduri de credit",
                                     "cash_on_delivery": "plata la livrare",
                                     "item_id": "item_id",
                                     "quantity": "quantity",
                                     "the_order_is_canceled": "comanda este anulata",
                                     "thank_you_for_your_order_the_item:": "multumesc pentru comanda ta articolul:",
                                     "will_reach_you_within_5_business_days": "va ajunge la dvs. in 5 zile lucratoare, costul comenzii este",
                                     "the_details_you_entered_are_incorrect_try_again": "detaliile pe care le-ați introdus sunt incorecte, încercați din nou",
                                     "user_with_this_email_does_not_exist_please_try_again": "utilizatorul cu acest e-mail nu există, vă rugăm să încercați din nou",
                                     "you_have_exceeded_the_maximum_number_of_attempts_please_try_again_later": "ați depășit numărul maxim de încercări, vă rugăm să încercați din nou mai târziu",
                                     "total_amount_to_be_chared:": "suma totala de perceput:",
                                     "invalid_installment_option_please_try_again": "opțiune nevalidă de rate, vă rugăm să încercați_din nou",
                                     "each_installment_will_be:": "fiecare tranșă va fi: ",
                                     "for_each": "pentru fiecare",
                                     "month": "lună",
                                     "operation_canceled": "operațiune anulată",
                                     "ivalid_input_please_enter_a_16_digit_number": "introducere nevalidă, introduceți un număr de 16 cifre",
                                     "please_enter_expiration_date_of_your_credit_card_(MM/YYYY)_or_0_to_cancel": "introduceți data de expirare a cardului dvs. de credit (LL/AAAA) sau 0 pentru a anula",
                                     "invalid_input_please_enter_a_vaild_expiration_date": "introducere nevalidă, introduceți o dată de expirare validă",
                                     "credit_card_has_expired_please_enter_a_vaild_expiration_date": "cardul de credit a expirat vă rugăm să introduceți o dată de expirare validă",
                                     "credit_card_expiration_date_is_valid": "data de expirare a cardului de credit este valabilă",
                                     "please_enter_the_last_three_digits_on_the_back_of_the_card_or_0_to_cancel": "vă rugăm să introduceți ultimele trei cifre de pe spatele cardului sau 0 pentru a anula",
                                     "invalid_input_please_enter_a_3_digit_number": "introducere nevalidă, introduceți un număr din 3 cifre",
                                     "ordered_successfully_the_receipt_will_be_sent_to": "comandat cu succes se va trimite chitanta catre",
                                     "thank_you_for_your_order_the_order_will_delivery_to:": "mulțumesc pentru comandă la care va fi livrată comanda:",
                                     "total_amount_to_be_charged:": "suma totală de perceput: ",
                                     "the_order_will_send_to_your_address_untill_5_days": "comanda va fi trimisa la adresa dumneavoastra pana in 5 zile",
                                     "what_you_entered_is_invalid_please_try_again_you_can_choose_1_or_2_or_3": "ceea ce ați introdus nu este valid, vă rugăm să încercați din nou, puteți alege 1 sau 2 sau 3",
                                     "looks_like_you_haven't_ordered_here_before": "se pare că nu ai mai comandat aici",
                                     "now_,_choose_new_status": "acum, alegeți un nou statut",
                                     "processing": "prelucrare",
                                     "shipped": "expediat", "delivered": "livrat",
                                     "try_again_error_in_choice": "încercați din nou eroare la alegere",
                                     "order_id_is_not_exist": "ID-ul comenzii nu există",
                                     "only_administrators_can_update_shipping_status": "numai administratorii pot actualiza starea expedierii",
                                     "you_are_not_logged_in_to_system": "nu sunteți autentificat la sistem",
                                     "total_revenue": "veniturile totale",
                                     "best_selling_product": "cel mai vandut produs",
                                     "best_profitable_product": "cel mai profitabil produs",
                                     "total_revenues_is:": "veniturile totale sunt: ",
                                     "the_best_seller_(in_quantity)_is:": "cel mai bine vandut (ca cantitate) este: ",
                                     "name": "Nume",
                                     "the_best_profitable_(in_money)_is:": "cel mai profitabil (în bani) este:",
                                     "money": "bani",
                                     "you_are_not_logged_in_to_system_or/and_you_are_not_admin_manager_of_store": "nu sunteți autentificat la sistem sau/și nu sunteți administratorul magazinului",
                                     "please_logout_and_then_try_to_redister_new_customer": "deconectați-vă și apoi încercați să înregistrați un client nou",
                                     "invalid_input_please_enter_a_10_digit_phone_number_containing_only_digits": "introducere nevalidă vă rugăm să introduceți un număr de telefon din 10 cifre care conține doar cifre",
                                     "user_id_is_exists_pleas_try_something_different": "ID-ul de utilizator există, vă rugăm să încercați ceva diferit",
                                     "registerd_successfully": "Inregistrare Reusita",
                                     "bye_bye!": "Pa! Pa!",
                                     "welcome,you_are_logged_in_now!": "bine ai venit, te-ai autentificat acum!",
                                     "wrong_details,please_try_again!": "detalii greșite, vă rugăm să încercați din nou!",
                                     "invalid_currency.please_try_again": "monedă invalidă. vă rugăm să încercați din nou",
                                     "you_must_be_logged_in_to_access_this_feature": "trebuie să fii autentificat pentru a accesa această funcție",
                                     "thank_you_for_using_our_system": "vă mulțumim că folosiți sistemul nostru",
                                     "Hello,welcome_to_our_furniture _store!": "Bună, bun venit în magazinul nostru de mobilă!",
                                     "Logout": "Deconectare", "Login": "Log in",
                                     "item_id_is_not_exist,please_try_again": "ID-ul articolului nu există, vă rugăm să încercați din nou",
                                     "add_review_and_rating_for_a_product": "adăugați recenzie și evaluare pentru un produs",
                                     "view_all_reviews_for_a_product": "vizualizați toate recenziile pentru un produs",
                                     "product_id_does_not_exist.": "ID-ul produsului nu există.",
                                     "invalid_choice.Please_try_again": "Alegere nevalidă. Vă rugăm să încercați din nou.",
                                     "there_is_no_maximum": "Nu există maxim",
                                     "enter_your_choice_to_make": "introduceți alegerea dvs. de făcut:",
                                     "please_enter_item_id:": "vă rugăm să introduceți id-ul articolului:",
                                     "please_enter_name:": "va rog introduceti numele:",
                                     "please_enter_description:": "va rog introduceti descrierea:",
                                     "please_enter_price:": "va rog introduceti pretul:",
                                     "please_enter_quantity:": "va rog introduceti cantitatea:",
                                     "please_enter_item_id_to_update:": "introduceți id-ul articolului pentru a actualiza:",
                                     "please_enter_new_name:": "vă rugăm să introduceți un nume nou:",
                                     "please_enter_new_quantity:": "vă rugăm să introduceți o nouă cantitate:",
                                     "please_enter_item_id_to_remove:": "introduceți id-ul articolului pentru a elimina:",
                                     "please_enter_your_address:": "zadejte prosím svou adresu:",
                                     "if_you_want_to_see_your_shopping_cart_and_buy_enter_Y_and_if_not_enter_N": "dacă vrei să-ți vezi coșul de cumpărături și să cumperi, introduceți Y și dacă nu introduceți N",
                                     "please_choose_payment_method:": "va rugam sa alegeti metoda de plata:",
                                     "enter_your_paypal_email_or_0_to_cancel:": "introduceți e-mailul dvs. paypal sau 0 pentru a anula:",
                                     "enter_your_paypal_password: ": "introduceți parola PayPal:",
                                     "choose_installment_option_(1,2,3):": "alegeți opțiunea de rate (1 ,2, 3):",
                                     "please_enter_your_16_digit_credit_card_number_or_0_to_cancel:": "introduceți numărul cardului dvs. de credit din 16 cifre sau 0 pentru a anula:",
                                     "please_enter_the_expiration_date_of_your_credit_card_(mm/yyyy)_or_0_to_cancel:": "introduceți data de expirare a cardului dvs. de credit (LL/AAAA) sau 0 pentru a anula:",
                                     "please_enter_the_last_three_digits_on_the_back_of_the_card_or_0_to_cancel:": "vă rugăm să introduceți ultimele trei cifre de pe spatele cardului sau 0 pentru a anula:",
                                     "enter_order_id_to_update:": "Introduceți ID-ul comenzii pentru a actualiza:",
                                     "please_enter_full_name:": "Vă rugăm să introduceți numele complet:",
                                     "please_enter_password:": "Te rog introdu parola:",
                                     "please_enter_phone:": "Vă rugăm să introduceți telefonul:",
                                     "please_enter_phone_or_type_exit_to_quit:": "Introduceți telefonul sau tastați exit pentru a ieși:",
                                     "please_enter_email:": "Vă rugăm să introduceți adresa de e-mail:",
                                     "please_enter_your_address,city_and_street:": "Vă rugăm să introduceți adresa, orașul și strada dvs.:",
                                     "please_enter_id:": "Vă rugăm să introduceți id:",
                                     "enter_your_the_product_id:": "Introduceți ID-ul produsului:",
                                     "enter_your_review:": "Introdu recenzia ta:",
                                     "enter_your_rating(1-5):": "introduceți evaluarea dvs. (1-5):",
                                     "please_enter_new_description:": "Vă rugăm să introduceți o nouă descriere:",
                                     "please_enter_new_price:": "Vă rugăm să introduceți un preț nou:",
                                     "enter_status_to_update:": "Introduceți starea pentru a actualiza:",
                                     "Your_shopping_cart_is_empty": "Cosul de cumparaturi este gol",
                                     "user_with_this_email_does_not_exist_Pleas_try_again": "utilizatorul cu acest e-mail nu există Vă rugăm să încercați din nou",
                                     "invalid_input_Pleas_enter_a_16_digit_number": "introducere nevalidă Vă rugăm să introduceți un număr de 16 cifre",
                                     "user_with_this_email_does_not_exist_Pleas_try_again": "utilizatorul cu acest e-mail nu există Vă rugăm să încercați din nou",
                                     "you_have_exceeded_the_maximum_number_of_attempts_Pleas_try_again_later": "ați depășit numărul maxim de încercări Vă rugăm să încercați din nou mai târziu",
                                     "choose_several_payments": "alegeți mai multe plăți:",
                                     "1/2/3": "1/2/3", "every_month_for": "în fiecare lună pt",
                                     "the_order_will_be_send_to_your_address_untill_5_days": "comanda va fi trimisa la adresa dumneavoastra pana in 5 zile",
                                     "invalid_input_Please_enter_a_valid_expiration_data": "introducere nevalidă Vă rugăm să introduceți date valide de expirare",
                                     "please_enter_valid_price_and_quantity": "va rugam sa introduceti pretul si cantitatea valabile",
                                     "please_enter_your_address,city_and_street": "vă rugăm să introduceți adresa orașul și strada",
                                     "please_logout_and_then_try_to_register_new_customer": "vă rugăm să deconectați-vă și apoi să încercați să înregistrați un nou vcustomer",
                                     "Now_,_choose_new_status": "Acum, alegeți un nou statut",
                                     "Please_enter_a_whole_number": "Vă rugăm să introduceți un număr întreg",
                                     "Review_added_successfully.": "Recenzie adăugată cu succes."},

                        "czech": {"product_management": "management de produs",
                                  "order_processing": "Procesarea comenzilory",
                                  "reporting": "raportare",
                                  "user_registration": "Înregistrare utilizator",
                                  "login_logout": "autentificare deconectare",
                                  "change_language_currency": "schimba moneda limbii",
                                  "reviews": "recenzii",
                                  "exit": "Ieșire",
                                  "view_available_products": "vizualizați produsele disponibile",
                                  "view_all_customers": "vizualiza toti clientii",
                                  "add_new_product": "adăugați un produs nou",
                                  "update_existing_product": "actualizați produsul existent",
                                  "remove_product": "scoateți produsul",
                                  "exit": "Ieșire",
                                  "item_id_is_exist_please_try_again": "ID-ul articolului există, încercați din nou",
                                  "added_successfully": "adăugat cu succes",
                                  "updated_successfully": "úspěšně aktualizováno",
                                  "removed_successfully": "úspěšně odstraněno",
                                  "try_again_error_in_choice": "zkuste to znovu chyba ve výběru",
                                  "you_are_not_logged_in_to_system_or_and_you_are_not_admin_manager_of_store": "nejste přihlášeni do systému nebo nejste správcem obchodu",
                                  "make_an_order": "udělat objednávku",
                                  "view_order_history": "zobrazit historii objednávek",
                                  "update_order_status": "aktualizovat stav objednávky",
                                  "update_order_status_success": "aktualizovatd vff fstav objednávky",
                                  "this_is_the_list_of_product_for_purchase": "**toto je seznam produktů ke koupi**",
                                  "enter_0_in_item_id_to_stop": "pro zastavení zadejte do ID položky 0",
                                  "there_is_not_enough_quantity_of_this_product": "není dostatečné množství tohoto produktu",
                                  "added_to_order_successfully": "úspěšně přidáno k objednávce",
                                  "the_product_order_process_has_been_stopped": "proces objednávky produktu byl zastaven",
                                  "quantity_for_item": "množství pro položku",
                                  "if you want to see your shopping cart and buy enter Y and if not enter N": "pokud chcete vidět svůj nákupní košík a koupit, zadejte Y a pokud ne, zadejte N",
                                  "what_you_typed_is_invalid_please_try_again": "to, co jste zadali, je neplatné, zkuste to znovu",
                                  "pay_pal": "zaplatit kamaráde",
                                  "credit_cards": "kreditní karty",
                                  "cash_on_delivery": "dobírka",
                                  "item_id": "item_id",
                                  "quantity": "quantity",
                                  "the_order_is_canceled": "objednávka je zrušena",
                                  "thank_you_for_your_order_the_item:": "děkujeme za Vaši objednávku zboží:",
                                  "will_reach_you_within_5_business_days": "obdržíte do 5 pracovních dnů, cena objednávky je",
                                  "the_details_you_entered_are_incorrect_try_again": "zadané údaje jsou nesprávné, zkuste to znovu",
                                  "user_with_this_email_does_not_exist_please_try_again": "uživatel s tímto e-mailem neexistuje, zkuste to znovu",
                                  "you_have_exceeded_the_maximum_number_of_attempts_please_try_again_later": "překročili jste maximální počet pokusů, zkuste to znovu později",
                                  "total_amount_to_be_chared:": "celková částka k zaplacení:",
                                  "invalid_installment_option_please_try_again": "neplatná možnost splátek, zkuste to znovu",
                                  "each_installment_will_be:": "každá splátka bude: ",
                                  "for_each": "pro každého",
                                  "month": "Měsíc",
                                  "operation_canceled": "operace zrušena",
                                  "ivalid_input_pleas_enter_a_16_digit_number": "neplatný vstup zadejte 16místné číslo",
                                  "please_enter_expiration_date_of_your_credit_card_(MM/YYYY)_or_0_to_cancel": "zadejte prosím datum vypršení platnosti vaší kreditní karty (MM/RRRR) nebo 0 pro zrušení",
                                  "invalid_input_please_enter_a_vaild_expiration_date": "neplatný vstup zadejte platné datum vypršení platnosti",
                                  "credit_card_has_expired_please_enter_a_vaild_expiration_date": "Platnost kreditní karty vypršela, zadejte prosím platné datum vypršení platnosti",
                                  "credit_card_expiration_date_is_valid": "datum vypršení platnosti kreditní karty je platné",
                                  "please_enter_the_last_three_digits_on_the_back_of_the_card_or_0_to_cancel": "zadejte prosím poslední tři číslice na zadní straně karty nebo 0 pro zrušení",
                                  "invalid_input_pleas_enter_a_3_digit_number": "neplatné zadání zadejte 3místné číslo",
                                  "ordered_successfully_the_receipt_will_be_sent_to": "úspěšně objednáno, účtenka bude odeslána na",
                                  "thank_you_for_your_order_the_order_will_delivery_to:": "Děkujeme za Vaši objednávku! objednávka bude doručena do: ",
                                  "total_amount_to_be_charged:": "celková částka, která má být účtována: ",
                                  "the_order_will_send_to_your_address_untill_5_days": "objednávka bude odeslána na vaši adresu do 5 dnů",
                                  "what_you_entered_is_invalid_please_try_again_you_can_choose_1_or_2_or_3": "to, co jste zadali, je neplatné, zkuste to znovu, můžete vybrat 1 nebo 2 nebo 3",
                                  "looks_like_you_haven't_ordered_here_before": "vypadá to, že jste si zde ještě neobjednali",
                                  "now_,_choose_new_status": "nyní vyberte nový stav",
                                  "processing": "zpracovává se",
                                  "shipped": "odesláno", "delivered": "doručeno",
                                  "try_again_error_in_choice": "zkuste to znovu chyba ve výběru",
                                  "order_id_is_not_exist": "ID objednávky neexistuje",
                                  "only_administrators_can_update_shipping_status": "stav zásilky mohou aktualizovat pouze správci",
                                  "you_are_not_logged_in_to_system": "nejste přihlášeni do systému",
                                  "total_revenue": "celkové příjmy",
                                  "best_selling_product": "nejprodávanější produkt",
                                  "best_profitable_product": "nejlépe ziskový produkt",
                                  "total_revenues_is:": "celkové výnosy jsou: ",
                                  "the_best_seller_(in_quantity)_is:": "nejprodávanější (v množství) je",
                                  "name": "název",
                                  "the_best_profitable_(in_money)_is:": "nejlépe ziskové (v penězích) je:",
                                  "money": "peníze",
                                  "you_are_not_logged_in_to_system_or/and_you_are_not_admin_manager_of_store": "nejste přihlášeni do systému nebo/a nejste správcem obchodu",
                                  "please_logout_and_then_try_to_redister_new_customer": "prosím odhlaste se a poté zkuste zaregistrovat nového zákazníka",
                                  "invalid_input_please_enter_a_10_digit_phone_number_containing_only_digits": "neplatné zadání zadejte 10místné telefonní číslo obsahující pouze číslice",
                                  "user_id_is_exists_please_try_something_different": "ID uživatele existuje, zkuste něco jiného",
                                  "registerd_successfully": "úspěšně zaregistrován",
                                  "bye_bye!": "Ahoj!",
                                  "welcome,you_are_logged_in_now!": "vítejte, nyní jste přihlášeni!",
                                  "wrong_details,please_try_again!": "špatné údaje, zkuste to prosím znovu!",
                                  "invalid_currency.please_try_again": "neplatná_měna. prosím_zkuste to znovu",
                                  "you_must_be_logged_in_to_access_this_feature": "pro přístup k této funkci musíte být přihlášeni",
                                  "thank_you_for_using_our_system": "děkujeme, že používáte náš systém",
                                  "Hello,welcome_to_our_furniture _store!": "Dobrý den, vítejte v našem obchodě s nábytkem!",
                                  "Logout": "Odhlásit se", "Login": "Přihlásit se",
                                  "item_id_is_not_exist,please_try_again": "ID položky neexistuje, zkuste to prosím znovu",
                                  "add_review_and_rating_for_a_product": "přidat recenzi a hodnocení produktu",
                                  "view_all_reviews_for_a_product": "zobrazit všechny recenze produktu",
                                  "product_id_does_not_exist.": "ID produktu neexistuje.",
                                  "invalid_choice.Please_try_again": "Neplatná volba. Zkuste to prosím znovu.",
                                  "there_is_no_maximum": "Neexistuje žádné maximum",
                                  "enter_your_choice_to_make": "zadejte svou volbu, kterou chcete provést:",
                                  "please_enter_item_id:": "zadejte prosím ID položky:",
                                  "please_enter_name:": "zadejte prosím jméno:",
                                  "please_enter_description:": "zadejte prosím popis:",
                                  "please_enter_price:": "prosím zadejte cenu:",
                                  "please_enter_quantity:": "zadejte množství:",
                                  "please_enter_item_id_to_update:": "prosím zadejte ID položky pro aktualizaci:",
                                  "please_enter_new_name:": "zadejte nové jméno:",
                                  "please_enter_new_quantity:": "zadejte nové množství:",
                                  "please_enter_item_id_to_remove:": "zadejte ID položky, kterou chcete odstranit:",
                                  "please_enter_your_address:": "zadejte prosím svou adresu:",
                                  "if_you_want_to_see_your_shopping_cart_and_buy_enter_Y_and_if_not_enter_N": "pokud chcete vidět svůj nákupní košík a koupit, zadejte Y a pokud ne, zadejte N",
                                  "please_choose_payment_method:": "prosím vyberte způsob platby:",
                                  "enter_your_paypal_email_or_0_to_cancel:": "zadejte svůj paypal email nebo 0 pro zrušení:",
                                  "enter_your_paypal_password:": "zadejte své heslo PayPal:",
                                  "choose_installment_option_(1,2,3):": "vyberte možnost splátek (1 , 2, 3):",
                                  "please_enter_your_16_digit_credit_card_number_or_0_to_cancel:": "pro zrušení zadejte 16místné číslo kreditní karty nebo 0:",
                                  "please_enter_the_expiration_date_of_your_credit_card_(mm/yyyy)_or_0_to_cancel:": "zadejte prosím datum vypršení platnosti vaší kreditní karty (MM/RRRR) nebo 0 pro zrušení:",
                                  "please_enter_the_last_three_digits_on_the_back_of_the_card_or_0_to_cancel:": "zadejte prosím poslední tři číslice na zadní straně karty nebo 0 pro zrušení:",
                                  "enter_order_id_to_update:": "Pro aktualizaci zadejte ID objednávky:",
                                  "please_enter_full_name:": "Zadejte prosím celé jméno:",
                                  "please_enter_password:": "Prosím vložte heslo:",
                                  "please_enter_phone:": "Zadejte prosím telefon:",
                                  "please_enter_phone_or_type_exit_to_quit:": "Pro ukončení prosím zadejte telefon nebo napište exit:",
                                  "please_enter_email:": "Zadejte prosím email:",
                                  "please_enter_your_address,city_and_street:": "Zadejte prosím svou adresu, město a ulici:",
                                  "please_enter_id:": "Zadejte id:",
                                  "enter_your_the_product_id:": "Zadejte své ID produktu:",
                                  "enter_your_review:": "Zadejte svou recenzi:",
                                  "enter_your_rating(1-5):": "zadejte své hodnocení (1-5):",
                                  "please_enter_new_description:": "Zadejte nový popis:",
                                  "please_enter_new_price:": "Zadejte prosím novou cenu:",
                                  "enter_status_to_update:": "Pro aktualizaci zadejte stav:",
                                  "Your_shopping_cart_is_empty": "Váš nákupní košík je prázdný",
                                  "invalid_input_Pleas_enter_a_16_digit_number": "neplatné zadání Zadejte 16místné číslo",
                                  "user_with_this_email_does_not_exist_Pleas_try_again": "uživatel s tímto e-mailem neexistuje. Zkuste to znovu",
                                  "user_with_this_email_does_not_exist_Pleas_try_again": "uživatel s tímto e-mailem neexistuje. Zkuste to znovu",
                                  "you_have_exceeded_the_maximum_number_of_attempts_Pleas_try_again_later": "překročili jste maximální počet pokusů Zkuste to znovu později",
                                  "choose_several_payments": "vybrat několik plateb:",
                                  "1/2/3": "1/2/3", "every_month_for": "každý měsíc pro",
                                  "the_order_will_be_send_to_your_address_untill_5_days": "objednávka bude odeslána na vaši adresu do 5 dnů",
                                  "invalid_input_Please_enter_a_valid_expiration_data": "neplatný vstup Zadejte prosím platná data vypršení platnosti",
                                  "please_enter_valid_price_and_quantity": "zadejte platnou cenu a množství",
                                  "user_id_is_exists_pleas_try_something_different": "ID uživatele existuje, zkuste něco jiného",
                                  "please_enter_your_address,city_and_street": "zadejte prosím svou adresu město a ulici",
                                  "please_logout_and_then_try_to_register_new_customer": "prosím odhlaste se a poté zkuste zaregistrovat nového zákazníka v",
                                  "Now_,_choose_new_status": "Nyní vyberte nový stav",
                                  "Please_enter_a_whole_number": "Zadejte prosím celé číslo",
                                  "Review_added_successfully.": "Recenze byla úspěšně přidána."},

                        "english": {"product_management": "product managements",
                                    "order_processing": "order processing",
                                    "reporting": "reporting",
                                    "user_registration": "user registration",
                                    "login_logout": "login logout",
                                    "change_language_currency": "change language currency",
                                    "reviews": "reviews",
                                    "view_available_products": "view available products",
                                    "view_all_customers": "view all customers",
                                    "add_new_product": "add new product",
                                    "update_existing_product": "update existing product",
                                    "remove_product": "remove product",
                                    "exit": "Exit",
                                    "item_id_is_exist_please_try_again": "item id is not exist please try again",
                                    "added_successfully": "added successfully",
                                    "updated_successfully": "updated successfully",
                                    "removed_successfully": "removed successfully",
                                    "try_again_error_in_choice": "try again error in choice",
                                    "you_are_not_logged_in_to_system_or_and_you_are_not_admin_manager_of_store": "you are not logged in to system or/and you are not admin manager of store",
                                    "make_an_order": "make an order",
                                    "view_order_history": "view order history",
                                    "update_order_status": "update order status",
                                    "update_order_status_success": "update order status success",
                                    "this_is_the_list_of_product_for_purchase": "**this is the list of product for purchase**",
                                    "enter_0_in_item_id_to_stop": "enter 0 in item id to stop",
                                    "there_is_not_enough_quantity_of_this_product": "there is not enough quantity of this product",
                                    "added_to_order_successfully": "added to order successfully",
                                    "the_product_order_process_has_been_stopped": "the product order process has been stopped",
                                    "quantity_for_item": "quantity for item",
                                    "if_you_want_to_see_your_shopping_cart_and_buy_enter_Y_and_if_not_enter_N": "if you want to see your shopping cart and buy enter Y and if not enter N",
                                    "what_you_typed_is_invalid_pleas_try_again": "what you typed is invalid pleas try again",
                                    "pay_pal": "Pay Pal",
                                    "credit_cards": "credit cards",
                                    "cash_on_delivery": "cash on delivery",
                                    "item_id": "item_id",
                                    "quantity": "quantity",
                                    "the_order_is_canceled": "the order is canceled",
                                    "thank_you_for_your_order_the_item:": "thank you for your order the item",
                                    "will_reach_you_within_5_business_days": "will reach you within 5 business days, the cost of the order is",
                                    "the_details_you_entered_are_incorrect_try_again": "the details you entered are incorrect try again",
                                    "user_with_this_email_does_not_exist_Pleas_try_again": "user with this email does not exist Please try again",
                                    "user_with_this_email_does_not_exist_pleas_try_again": "user with this email does not exist please try again",
                                    "you_have_exceeded_the_maximum_number_of_attempts_pleas_try_again_later": "you have exceeded the maximum number of attempts please try again later",
                                    "total_amount_to_be_chared:": "total amount to be chared:",
                                    "invalid_installment_option_pleas_try_again": "invalid installment option please try again",
                                    "each_installment_will_be:": "each installment will be: ",
                                    "for_each": "for each",
                                    "month": "month",
                                    "operation_canceled": "operation canceled",
                                    "ivalid_input_pleas_enter_a_16_digit_number": "ivalid input please enter a 16 digit number",
                                    "please_enter_expiration_date_of_your_credit_card_(MM/YYYY)_or_0_to_cancel": "please enter expiration date of your credit card (MM/YYYY) or 0 to cancel",
                                    "invalid_input_please_enter_a_vaild_expiration_date": "invalid input please enter a vaild expiration date",
                                    "credit_card_has_expired_please_enter_a_vaild_expiration_date": "credit card has expired please enter a vaild expiration date",
                                    "credit_card_expiration_date_is_valid": "credit card expiration date is valid",
                                    "please_enter_the_last_three_digits_on_the_back_of_the_card_or_0_to_cancel": "please enter the last three digits on the back of the card or 0 to cancel",
                                    "invalid_input_please_enter_a_3_digit_number": "invalid input please enter a 3 digit_number",
                                    "ordered_successfully_the_receipt_will_be_sent_to": "ordered successfully the receipt will be sent to",
                                    "thank_you_for_your_order_the_order_will_delivery_to:": "thank you for your order the order will delivery to: ",
                                    "total_amount_to_be_charged:": "total amount to be charged: ",
                                    "the_order_will_send_to_your_address_untill_5_days": "the order will send to your address untill 5 days",
                                    "total_amount_to be_charged:": "what you entered is invalid please try again you can choose 1 or 2 or 3",
                                    "looks_like_you_haven't_ordered_here_before": "looks like you haven't ordered here before",
                                    "now_,_choose_new_status": "now, choose new status",
                                    "processing": "processing",
                                    "shipped": "shipped", "delivered": "delivered",
                                    "try_again_error_in_choice": "try again error in choice",
                                    "order_id_is_not_exist": "order id is not exist",
                                    "only_administrators_can_update_shipping_status": "only administrators can update shipping status",
                                    "you_are_not_logged_in_to_system": "you are not logged in to system",
                                    "total_revenue": "total revenue",
                                    "best_selling_product": "best selling product",
                                    "best_profitable_product": "best profitable product",
                                    "total_revenues_is:": "total revenues is: ",
                                    "the_best_seller_(in_quantity)_is:": "the best seller (in quantity) is:",
                                    "name": "name",
                                    "the_best_profitable_(in_money)_is:": "the best profitable (in money) is:",
                                    "money": "money",
                                    "you_are_not_logged_in_to_system_or/and_you_are_not_admin_manager_of_store": "you are not logged in to system or/and you are not admin manager of store",
                                    "please_logout_and_then_try_to_redister_new_customer": "please logout and then try to redister new customer",
                                    "invalid_input_please_enter_a_10_digit_phone_number_containing_only_digits": "invalid input please enter a 10 digit phone number containing only digits",
                                    "user_id_is_exists_pleas_try_something_different": "user id is exists please try something different",
                                    "registerd_successfully": "registerd successfulln",
                                    "bye_bye!": "bye bye!",
                                    "welcome,you_are_logged_in_now!": "welcome,you are logged in now!",
                                    "wrong_details,pleas_try_again!": "wrong details, please try again!",
                                    "invalid_currency.please_try_again": "invalid currency. please try again",
                                    "you_must_be_logged_in_to_access_this_feature": "you must be logged in to access this feature",
                                    "thank_you_for_using_our_system": "thank you for using our_system",
                                    "Hello,welcome_to_our_furniture _store!": "Hello, welcome to our furniture store!",
                                    "Logout": "Logout", "Login": "login",
                                    "item_id_is_not_exist,please_try_again": "item id is not exist, please try again",
                                    "add_review_and_rating_for_a_product": "add review and rating for a product",
                                    "view_all_reviews_for_a_product": "view all reviews for a product",
                                    "product_id_does_not_exist.": "Product ID does not exist.",
                                    "invalid_choice.Please_try_again": "Invalid choice. Please try again.",
                                    "there_is_no_maximum": "There is no maximum",
                                    "enter_your_choice_to_make": "enter your choice to make:",
                                    "please_enter_item_id:": "Please enter item id:",
                                    "please_enter_name:": "Please enter name:",
                                    "please_enter_description:": "Please enter description:",
                                    "please_enter_price:": "Please enter price:",
                                    "please_enter_quantity:": "Please enter quantity:",
                                    "please_enter_item_id_to_update:": "Please enter item id to update:",
                                    "please_enter_new_name:": "Please enter new name:",
                                    "please_enter_new_quantity:": "Please enter new quantity:",
                                    "please_enter_item_id_to_remove:": "Please enter item id to remove:",
                                    "please_enter_your_address:": "Please enter your address:",
                                    "if_you_want_to_see_your_shopping_cart_and_buy_enter_Y_and_if_not_enter_N": "if you want to see your Shopping cart and buy enter Y and if not enter N",
                                    "please_choose_payment_method:": "Please choose payment method:",
                                    "enter_your_paypal_email_or_0_to_cancel:": "enter your paypal email or 0 to cancel:",
                                    "enter_your_paypal_password:": "enter your PayPal password: ",
                                    "choose_installment_option_(1,2,3):": "choose installment option (1 ,2, 3):",
                                    "please_enter_your_16_digit_credit_card_number_or_0_to_cancel:": "Please enter your 16 digit credit card number or 0 to cancel:",
                                    "please_enter_the_expiration_date_of_your_credit_card_(mm/yyyy)_or_0_to_cancel:": "Please enter the expiration date of your credit card (MM/YYYY) or 0 to cancel:",
                                    "please_enter_the_last_three_digits_on_the_back_of_the_card_or_0_to_cancel:": "Please enter the last three digits on the back of the card or 0 to cancel:",
                                    "enter_order_id_to_update:": "Enter order id to update:",
                                    "please_enter_full_name:": "Please enter full name:",
                                    "please_enter_password:": "Please enter password:",
                                    "please_enter_phone:": "Please enter phone:",
                                    "please_enter_phone_or_type_exit_to_quit:": "Please enter phone or type 'exit' to quit:",
                                    "please_enter_email:": "Please enter email:",
                                    "please_enter_your_address,city_and_street:": "Please enter your address ,city and street:",
                                    "please_enter_id:": "Please enter id:",
                                    "enter_your_the_product_id:": "Enter your the product id:",
                                    "enter_your_review:": "Enter your review:",
                                    "enter_your_rating(1-5):": "Enter your rating (1-5):",
                                    "please_enter_new_description:": "Please enter new description:",
                                    "please_enter_new_price:": "Please enter new price:",
                                    "enter_status_to_update:": "Enter status to update:",
                                    "Your_shopping_cart_is_empty": "Your_shopping_cart_is_empty",
                                    "invalid_input_Pleas_enter_a_16_digit_number": "invalid input Pleas enter a 16 digit number",
                                    "choose_several_payments": "choose several payments:",
                                    "1/2/3": "1/2/3/", "every_month_for": "every month for",
                                    "the_order_will_be_send_to_your_address_untill_5_days": "the order will be send to your address untill 5 days",
                                    "invalid_input_Please_enter_a_valid_expiration_data": "invalid input Please enter a valid expiration data",
                                    "please_enter_valid_price_and_quantity": "please enter valid price and quantity",
                                    "please_logout_and_then_try_to_register_new_customer": "please logout and then try to register new customer",
                                    "Now_,_choose_new_status": "Now, choose new status",
                                    "Please_enter_a_whole_number": "Please enter a whole number",
                                    "Review_added_successfully.": "Review added successfully."}}

        return translations
